services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  authentication:
    build:
      context: .
      dockerfile: apps/authentication/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - apps/authentication/.env
    depends_on:
      - mongodb

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/gateway/.env
    depends_on:
      - authentication

volumes:
  mongo_data:
